# API to DataFrame

This notebook shows how to fetch JSON data from an API and convert it into a pandas DataFrame for analysis.

## 1. Import required libraries
Definition: We need `pandas` to create DataFrames and `requests` to call the API.

```python
import pandas as pd
import requests
```

Example output:
```text
# No visible output, just the libraries are imported.
```

## 2. Make an API request
Definition: Use the `requests.get()` method to fetch data from a public API endpoint.

```python
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=...&language=en-US&page=1')
```

Example output:
```text
<Response [200]>
```

## 3. Convert API JSON to DataFrame
Definition: Extract the `results` list from the JSON response and convert it into a DataFrame.

```python
temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
```

Example output:
```text
      id                 title                         overview               release_date  popularity   vote_average  vote_count
0    278     The Shawshank Redemption      ...             1994-09-23    110.5         8.7          24000
1    238     The Godfather                ...             1972-03-14    95.2          8.7          18000
```

## 4. View the DataFrame
Definition: Display the first few rows of the DataFrame using `head()`.

```python
df.head()
```

Example output:
```text
      id     title                 overview                 release_date  popularity  vote_average  vote_count
0    278    The Shawshank Redemption ...                   1994-09-23   110.5      8.7          24000
1    238    The Godfather           ...                   1972-03-14    95.2      8.7          18000
```

## 5. Collect multiple pages from the API
Definition: Loop through many pages of the API and append each page result to a single DataFrame.

```python
for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
    df = df.append(temp_df, ignore_index=True)
```

Example output:
```text
# No immediate printed output, but the DataFrame grows with each page.
```

## 6. Check dataset size
Definition: Use `.shape` to see how many rows and columns the DataFrame has.

```python
df.shape
```

Example output:
```text
(8560, 7)
```

## 7. Save DataFrame to CSV
Definition: Export the processed data into a CSV file for later use.

```python
df.to_csv('movies.csv')
```

Example output:
```text
# Creates a file named movies.csv in the current folder.
```

---

### Summary
API data is often returned as JSON. By using `requests` and `pandas`, we can fetch that data, convert it into a DataFrame, and save it for further analysis.

In [1]:
import pandas as pd
import requests

In [6]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [7]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [34]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773

In [17]:
df = pd.DataFrame()

In [18]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = df.append(temp_df,ignore_index=True)

In [21]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,18.433,8.7,2763
1,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,8.439,8.7,1223
2,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,65.570,8.7,18637
3,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,63.277,8.7,14052
4,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,26.691,8.7,773
...,...,...,...,...,...,...,...
8546,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,14.630,3.2,714
8547,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,10.647,3.0,543
8548,14164,Dragonball Evolution,The young warrior Son Goku sets out on a quest...,2009-03-12,32.244,2.8,1447
8549,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.502,2.8,238
8550,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,9.824,2.2,215

In [22]:
df.shape

(8551, 7)

In [23]:
df.to_csv('movies.csv')